management:
  context-path: /actuator

server:
  port: 8082

spring:
  application:
    name: book-api
  cloud:
    consul:
      discovery:
        instanceId: ${spring.application.name}:${random.value}
        healthCheckPath: ${management.context-path}/health
        healthCheckInterval: 15s

